services:
  app:
    build: .
    container_name: api-mini-banco-central
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/mbc
    depends_on:
      - postgres
    restart: unless-stopped
  
  postgres:
    image: postgres:17
    container_name: api_mbc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mbc
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
