services:
  postgres:
    image: postgres:17
    container_name: api_mbc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mbc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mbc_network

volumes:
  postgres_data:

networks:
  mbc_network:
    driver: bridge
